apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMDUuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImRtVnVhMkYwWlhOb09sWmxibXRoZEdWemFFQXhOREk9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
