apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMDUuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImRtVnVhMkYwWlhOb2EyOXVaR0V4TkRKQVoyMWhhV3d1WTI5dE9sWmxibXRoZEdWemFFQXhOREk9IgoJCX0sCgkJInZlbmthdGVzaGtvbmRhMTQyLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJkbVZ1YTJGMFpYTm9hMjl1WkdFeE5ESTZWbVZ1YTJGMFpYTm9RREUwTWc9PSIKCQl9Cgl9Cn0=
